apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /monitor
        pathType: ImplementationSpecific
        backend:
          service:
            name: prometheus-kube-prometheus-prometheus
            port:
              number: 9090
      - path: /observe
        pathType: ImplementationSpecific
        backend:
          service:
            name: grafana
            port:
              number: 80
      - path: /alerts
        pathType: ImplementationSpecific
        backend:
          service:
            name: prometheus-kube-prometheus-alertmanager
            port:
              number: 9093
