apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://mongodb.github.io/helm-charts
    chart: community-operator
    targetRevision: "0.9.0"
    helm:
      parameters:
        - name: auth.rootPassword
          value: your-root-password
        - name: architecture
          value: "standalone"
        - name: persistence.enabled
          value: "true"
        - name: persistence.size
          value: 8Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true