apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo
  namespace: default
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: myUser
      db: admin
      passwordSecretRef:
        name: myuser-password-secret
      roles:
        - name: readWrite
          db: mydatabase
